"""
lattice_math.py

Small mathematical toolkit for experimenting with lattices.

Conventions
-----------
- Basis vectors are COLUMNS of a matrix B.
- L(B) = {B z : z in Z^n}.
- All lattices live in R^2 and have rank 1 or 2.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import reduce
from itertools import combinations, product
from math import gcd

import numpy as np


def _as_matrix(A) -> np.ndarray:
    A = np.asarray(A, dtype=float)
    if A.ndim == 1:
        A = A.reshape(-1, 1)
    if A.ndim != 2:
        raise ValueError("Expected a vector or matrix.")
    return A


def _as_integer_matrix(A, tol: float = 1e-9) -> np.ndarray:
    A = np.asarray(A, dtype=float)
    rounded = np.rint(A)
    if not np.allclose(A, rounded, atol=tol, rtol=0):
        raise ValueError("Expected an integer matrix.")
    return rounded.astype(int)


def integer_grid(rank: int, radius: int) -> np.ndarray:
    """
    Return all integer coefficient vectors in [-radius, radius]^rank.

    Output shape: (rank, number_of_points)
    """
    coeffs = list(product(range(-radius, radius + 1), repeat=rank))
    return np.asarray(coeffs, dtype=int).T


def gcd_of_maximal_minors(A) -> int:
    """
    Compute gcd of all k x k minors of an integer n x k matrix A.

    If A has full column rank k, the sublattice generated by its columns
    inside Z^n is primitive iff this gcd is 1.
    """
    A = _as_integer_matrix(A)
    n, k = A.shape

    if k > n:
        raise ValueError("A cannot have more columns than rows.")

    if np.linalg.matrix_rank(A) < k:
        return 0

    determinants = []
    for rows in combinations(range(n), k):
        minor = A[list(rows), :]
        # determinant is mathematically integral; round numerical result
        det = int(round(np.linalg.det(minor)))
        determinants.append(abs(det))

    return reduce(gcd, determinants, 0)


def is_primitive_coordinate_matrix(A) -> bool:
    """
    Decide whether columns of integer n x k matrix A generate a primitive
    rank-k sublattice of Z^n.

    Criterion:
        gcd(all k x k minors of A) == 1.
    """
    A = _as_integer_matrix(A)
    return gcd_of_maximal_minors(A) == 1


@dataclass(frozen=True)
class Lattice:
    """
    A lattice L(B) in R^2 with basis vectors stored as columns of B.
    """

    basis: np.ndarray

    def __post_init__(self):
        B = _as_matrix(self.basis)

        if B.shape[0] != 2:
            raise ValueError("Lattice basis must consist of vectors in R^2.")

        if np.linalg.matrix_rank(B) != B.shape[1]:
            raise ValueError("Basis columns must be linearly independent.")

        object.__setattr__(self, "basis", B)

    @property
    def ambient_dimension(self) -> int:
        return 2

    @property
    def rank(self) -> int:
        return self.basis.shape[1]

    @property
    def gram(self) -> np.ndarray:
        """Gram matrix G = B^T B."""
        return self.basis.T @ self.basis

    @property
    def is_full_rank(self) -> bool:
        return self.rank == 2

    @property
    def covolume(self) -> float:
        """
        Volume of a fundamental parallelepiped:
            sqrt(det(B^T B)).

        For a square full-rank basis this equals |det(B)|.
        """
        return float(np.sqrt(np.linalg.det(self.gram)))

    @property
    def dual_basis(self) -> np.ndarray:
        """
        Dual basis:
            B* = B (B^T B)^(-1)

        If B is square:
            B* = B^(-T)
        """
        return self.basis @ np.linalg.inv(self.gram)

    @property
    def dual(self) -> "Lattice":
        return Lattice(self.dual_basis)

    def axis_range(
        self,
        axis: int,
        radius: int = 4,
        padding: float = 0.5,
    ) -> list[float]:
        """
        Axis range containing all lattice points Bz with
        z_i in [-radius, radius].
        """
        extent = radius * np.sum(np.abs(self.basis[axis, :]))

        return [
            float(-extent - padding),
            float(extent + padding),
        ]

    def x_range(
        self,
        radius: int = 4,
        padding: float = 0.5,
    ) -> list[float]:
        return self.axis_range(0, radius, padding)

    def y_range(
        self,
        radius: int = 4,
        padding: float = 0.5,
    ) -> list[float]:
        return self.axis_range(1, radius, padding)

    def vector(self, coefficients) -> np.ndarray:
        """
        Construct B z for integer coefficient vector z.
        """
        z = np.asarray(coefficients, dtype=float).reshape(-1)
        if z.size != self.rank:
            raise ValueError(f"Expected {self.rank} coefficients.")

        z_int = np.rint(z)
        if not np.allclose(z, z_int):
            raise ValueError("Lattice coefficients must be integers.")

        return self.basis @ z_int.astype(int)

    def points(self, radius: int = 4) -> np.ndarray:
        """
        Generate lattice points B z with each coefficient z_i in
        [-radius, radius].

        Output shape: (number_of_points, 2)
        """
        Z = integer_grid(self.rank, radius)
        return (self.basis @ Z).T

    def change_basis(self, U) -> "Lattice":
        """
        Return L(BU).

        If U is unimodular, this is the SAME lattice with a different basis.
        """
        U = _as_integer_matrix(U)

        if U.shape != (self.rank, self.rank):
            raise ValueError(
                f"U must have shape {(self.rank, self.rank)}."
            )

        return Lattice(self.basis @ U)

    def rotate(self, R) -> "Lattice":
        """
        Apply a linear map R to all basis vectors.

        If R is orthogonal, this is an isometric rotation/reflection.
        """
        R = _as_matrix(R)

        if R.shape != (2, 2):
            raise ValueError("R must be a 2 x 2 matrix.")

        return Lattice(R @ self.basis)

    def sublattice(self, A) -> "Lattice":
        """
        Build a sublattice using integer coordinate matrix A.

        If B is 2 x n and A is n x k, then
            B_sub = B A
        gives a rank-k sublattice (assuming independent columns).
        """
        A = _as_integer_matrix(A)

        if A.shape[0] != self.rank:
            raise ValueError(
                f"A must have {self.rank} rows (coordinates in parent basis)."
            )

        return Lattice(self.basis @ A)

    def is_primitive_sublattice(self, A) -> bool:
        """
        Test whether the sublattice L(BA) is primitive inside L(B).

        A must be an integer n x k coordinate matrix of full column rank.
        """
        A = _as_integer_matrix(A)

        if A.shape[0] != self.rank:
            raise ValueError(
                f"A must have {self.rank} rows (coordinates in parent basis)."
            )

        return is_primitive_coordinate_matrix(A)

    def nearest_point_bruteforce(self, target, radius: int = 5):
        """
        Brute-force nearest lattice point for small educational examples.

        This is NOT a serious CVP solver. It only searches coefficient vectors
        in [-radius, radius]^rank.
        """
        t = np.asarray(target, dtype=float).reshape(-1)

        if t.size != 2:
            raise ValueError("Target must live in R^2.")

        pts = self.points(radius)
        distances = np.linalg.norm(pts - t, axis=1)
        i = int(np.argmin(distances))
        return pts[i], float(distances[i])


def rotation_matrix_2d(theta_radians: float) -> np.ndarray:
    c = np.cos(theta_radians)
    s = np.sin(theta_radians)
    return np.array([
        [c, -s],
        [s,  c],
    ])

